name: home
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  awesome_dio_interceptor: ^1.2.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  flutter_tawk: ^0.1.0
  freezed_annotation: ^2.4.2
  get: ^4.6.6
  google_maps_flutter: ^2.7.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.9.0
  nb_utils: ^7.0.3
  photo_view: ^0.15.0
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  skeletonizer: ^1.3.0
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_app_rename: ^0.1.2

  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter_app_rename:
  name: "Home"
  id: "com.home.service"

flutter:

  uses-material-design: true

  assets:
    - assets/image-png/
    - assets/image-svg/
    - assets/images/
    - assets/setting/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  image_path: "assets/image-png/home_logo.png"
